// <auto-generated />
using System;
using ElectricityAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectricityAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260721184157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ElectricityAPI.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BlockNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BuildingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ConsumerType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EBill")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdProofNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IdProofPath")
                        .HasColumnType("longtext");

                    b.Property<string>("IdProofType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KhasraNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LandmarkDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LiftInstalled")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoadKVA")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LoadKW")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MeterType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NearestHouseNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OpenRooftop")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipProofPath")
                        .HasColumnType("longtext");

                    b.Property<string>("OwnershipProofType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PremisePortion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PremisesType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PropertyNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PurchaseMeter")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("SameAsCommunication")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyArea")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyBlockNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyFloor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyKhasraNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyLandmark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyLandmarkDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyPostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyPremisePortion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyPropertyNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplySector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyState")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SupplyStreet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TemporaryConnection")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
